version: "3.8"
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${TODAY_LIST_DB_PASSWORD}
      MYSQL_DATABASE: ${TODAY_LIST_DB_NAME}
      MYSQL_USER: ${TODAY_LIST_DB_USER}
      MYSQL_PASSWORD: ${TODAY_LIST_DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  nodejs:
    image: node:14
    build:
      context: ../
      dockerfile: ./deployment/nodejs/Dockerfile

    volumes:
      - ..:/usr/src/app
    working_dir: /usr/src/app
    environment:
      DB_HOST: ${TODAY_LIST_DB_HOST}
      DB_PORT: 3306
      DB_USERNAME: ${TODAY_LIST_DB_USER}
      DB_PASSWORD: ${TODAY_LIST_DB_PASSWORD}
      DB_NAME: ${TODAY_LIST_DB_NAME}

    command: bash -c "npm install && npm start"
    depends_on:
      - db
    networks:
      - mynetwork
    ports:
      - "3000:3000"

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - nodejs
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  db_data:
