FROM node:14

WORKDIR /usr/src/app

# 현재 디렉토리의 모든 파일과 폴더를 복사
COPY ./* ./

RUN npm install

EXPOSE 3000

COPY ./deployment/nodejs/wait-for-it.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/wait-for-it.sh


CMD ["npm", "start"]
